---
title: "Introduction to Bioconductor exercises"
author: "Rockefeller University, Bioinformatics Resource Centre"
date: "https://rockefelleruniversity.github.io/Bioconductor_Introduction/"
output: 
  html_document:
    number_sections: false  ## if you want number sections at each table header
    theme: united  # many options for theme, this one is my favorite.
    highlight: tango  # specifies the syntax highlighting style
params:
  toMessage: false    
---

```{r, setup,include=FALSE}
toMessage <- ifelse(!is.null(params$toMessage),params$toMessage,FALSE)
message(toMessage)
```


## Installing Bioconductor packages

These exercises will run us through the installation of some key packages.


1. Install the Biostrings package

```{r installBS, echo=toMessage}
install.packages("BiocManager")
require(BiocManager)
BiocManager::install("Biostrings",update = FALSE)
```

2. Check your Bioconductor version (should be `r BiocManager::version()`)

```{r installBS2, echo=toMessage}
BiocManager::version()
```

3. Install the BSgenome annotation package for mouse UCSC mm10 and human UCSC hg19.

```{r installBS23, echo=toMessage, eval=F}
BiocManager::install("BSgenome.Hsapiens.UCSC.hg19",update = FALSE)
BiocManager::install("BSgenome.Mmusculus.UCSC.mm10",update = FALSE)
```
